scss_files: 'source/_assets/stylesheets/*.scss'

exclude: 'source/_assets/stylesheets/main.scss'

linters:
  NameFormat:
    enabled: false
  UrlFormat:
    enabled: false
  VendorPrefix:
    enabled: false
